# Generated by Django 3.2.5 on 2021-07-16 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210716_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionitem',
            name='note',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
            preserve_default=False,
        ),
    ]
