# Generated by Django 3.2.5 on 2021-07-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_actionitem_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='private',
            new_name='private_flag',
        ),
    ]
